name: MagicItem
version: "1.1.4"
author: "mcayear"
authors: ["mcayear"]
load: STARTUP
api: ["1.0.0"]
main: cn.ankele.plugin.MagicItem
depend: ["EconomyAPI"]
softdepend: ["RcRPG"]
permissions:
  magicitem.command:
    description: "MagicItem 基本命令权限"
    default: true
  magicitem.command.op:
    description: "MagicItem 管理员命令权限"
    default: op
